### ISSUE TITLE
exasock doesn't support socket MSG_WAITALL flag

### ISSUE THREAD

**Issue by YungeG** [cisco/exanic-software#73]
Suppose following case:

**Server** wants to send a package of `1490` , which is split into `1460+30` .

**Client**

1. init a tcp socket
2. `recv` socket with flag **MSG_WAITALL** , and provide a length of **298**
3. with exasock , the first 4 `recv` will return with a length of **298**
4. the last `recv` will return **268** , even if the last 30 bytes will be received in following package

Is the case above possible ? How to deal with it ?

**Comment by badipietro** [comment]
This is a know limitation that MSG_WAITALL isn't supported with the exasock library.  The documentation is here:
https://www.cisco.com/c/en/us/td/docs/dcn/nexus3550/smartnic/sw/user-guide/cisco-nexus-smartnic-user-guide/sockets.html#known-issues-and-limitations

Since there is blocking with MSG_WAITALL and the application is likely not latency sensitive, an alternative might be to not accelerate that particular socket by setting the socket option: 
``       optval = 1;
       rc = setsockopt(sock, SOL_EXASOCK, SO_EXA_NO_ACCEL,  &optval, sizeof(optval));
       if (rc)
       {
          printf("Failed to set SOL_EXASOCK sockopt SO_EXA_NO_ACCEL %s (%d)\n", strerror(errno), rc);

       }
``

**Comment by YungeG** [comment]
Thanks for your reply.
